import { Themes } from './interface';


export const themes: Themes = {
    oceanicBlue: {
        headerColors: "#0078AB",
        mainColor: "#0096CE",
        textColor: "white",
        hoverColor: "#1C85B9",
        btnSettingsColor: "#0078AB",
        btnSettingsColorNotActive: "white",
        textActiveSettingsColor: "white",
        textNotActiveSettingsColor: "#0078AB",
        titleColorSettings: "white",
        headerSvgColor: "white",
        questionsGroupBackground: "white",
        btnSettingsBackgroundColor: "white",
        svgGroupColor: "#0078AB",
        svgAvtiveBackgroundColor: "#1C85B9",
        toggleBackground: "#d7d3d2",
        toggleBorder: "#0078A5",
        MockTestChartBackground: 'linear-gradient(180deg, rgba(126,198,212,1) 0%, rgba(0,150,206,1) 90%)',
        MockTestChartLabel: 'white',
        MockTestChartLinePath: '#32EBC3',
        MockTestChartPoints: 'white',
        DataStatisticsAssessmentTitle: 'white',
        DataStatisticsAssessmentContent: '#0078AB',
        DataStatisticsAssessmentFooter: '#0078AB',
        DataStatisticsAssessmentFooterTextbtn: "#0078AB",
        DataStatisticsAssessmentBackground: "white",
        DataStatisticsAssessmentFooterBackgroundBtn: "white",
        TestBackground: "rgb(0, 150, 206)",
        TestcolorText: 'rgb(0, 120, 171)',
        VariantTitleColor: "white",
        FlagColorSvgBtn: "#0078AB",
        QuestionContentBackground: "white",
        FooterBackgroundBtn: "#0078AB",
        VariantBackground: "white",
        VariantTextColor: "#0078AB",
        VariantSelectedOption: "white",
        VariantSelectedMockTestOption: "#0078AB",
        VariantSelectedMockBackground: "#FFEC4B",
        FooterBackgroundNextBtnSelectedOption: "#FFEC4B",
        FooterTextBtn:"white",
        FooterBackgroundBtnDesktop:"#FFFFFF",
        FooterColorNextBtnSelectedOption: "#0078AB",
        FooterTextBtnDesktop:"#0078AB",
        FooterFlagMobileButton:'#F9921A',
        HeaderPracticeTestQuestionColors: "white",
        OnceTwiceProgressOnesBackground: "#0079AC",
        CircularTrainerProgressBarColor: "#008BC8",
        HptTitleColorText: "#0078AB",
        HtpPlateBackground: "white",
        HtpIntroductionBtnBackground: "#0078AB",
        HtpIntroductionBtnTextColor: "white",
        HtpIconNumberBackground: "#0078AB",
    },
    amberSunset: {
        headerColors: "#F9931C",
        mainColor: "#FDCA3A",
        textColor: "white",
        hoverColor: "#FF9F30",
        btnSettingsColor: "#0078AB",
        btnSettingsColorNotActive: "white",
        textActiveSettingsColor: "white",
        textNotActiveSettingsColor: "#000000",
        titleColorSettings: "#000000",
        headerSvgColor: "white",
        questionsGroupBackground: "white",
        btnSettingsBackgroundColor: "white",
        svgGroupColor: "#000000",
        svgAvtiveBackgroundColor: "#FF9F30",
        toggleBackground: "#FDC93A",
        toggleBorder: "#C9A12E",
        MockTestChartBackground: 'linear-gradient(180deg, rgba(255,234,166,1) 0%, rgba(253,201,58,1) 90%)',
        MockTestChartLabel: '#000000',
        MockTestChartLinePath: '#000000',
        MockTestChartPoints: '#F9931C',
        DataStatisticsAssessmentTitle: '#000000',
        DataStatisticsAssessmentContent: '#000000',
        DataStatisticsAssessmentFooter: '#F9931C',
        DataStatisticsAssessmentFooterTextbtn: "#000000",
        DataStatisticsAssessmentBackground: "white",
        DataStatisticsAssessmentFooterBackgroundBtn: "white",
        TestBackground: "#FDCA3A",
        TestcolorText: '#000000',
        VariantTitleColor: "#000000",
        FlagColorSvgBtn: "#000000",
        QuestionContentBackground: "white",
        FooterBackgroundBtn: "#F9931C",
        FooterTextBtn:"white",
        FooterBackgroundBtnDesktop:"#FFFFFF",
        FooterTextBtnDesktop:"#000000",
        FooterFlagMobileButton:'#fdca3a',
        VariantBackground: "white",
        VariantTextColor: "#000000",
        VariantSelectedOption: "white",
        VariantSelectedMockTestOption: "#000000",
        VariantSelectedMockBackground: "#FFEC4B",
        FooterBackgroundNextBtnSelectedOption: "#FFEC4B",
        FooterColorNextBtnSelectedOption: "#000000",
        HeaderPracticeTestQuestionColors: "white",
        OnceTwiceProgressOnesBackground: "#F9921D",
        CircularTrainerProgressBarColor: "#FFF9D0",
        HptTitleColorText: "#000000",
        HtpPlateBackground: "white",
        HtpIntroductionBtnBackground: "#F9931C",
        HtpIntroductionBtnTextColor: "white",
        HtpIconNumberBackground: "#0078AB",
    },
    frostedPearl: {
        headerColors: "#F9F9F9",
        mainColor: "#F2F2F6",
        textColor: "#0A0A0A",
        btnSettingsColor: "#000000",
        btnSettingsColorNotActive: "white",
        hoverColor: "#EBEBEB",
        textActiveSettingsColor: "white",
        textNotActiveSettingsColor: "#000000",
        titleColorSettings: "#000000",
        headerSvgColor: "#000000",
        questionsGroupBackground: "white",
        btnSettingsBackgroundColor: "white",
        svgGroupColor: "#000000",
        svgAvtiveBackgroundColor: "#EBEBEB",
        toggleBackground: "#F3F3F6",
        toggleBorder: "#C2C2C5",
        QuestionContentBackground: "white",
        VariantBackground: "white",
        VariantTextColor: "#000000",
        VariantSelectedOption: "white",
        VariantSelectedMockTestOption: "white",
        VariantSelectedMockBackground: "#AAAAAA",
        MockTestChartBackground: 'linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(243,243,246,1) 90%)',
        MockTestChartLabel: "#000000",
        MockTestChartLinePath: "#000000",
        MockTestChartPoints: "#000000",
        DataStatisticsAssessmentTitle: "#000000",
        DataStatisticsAssessmentContent: "#000000",
        DataStatisticsAssessmentFooter: "#F9F9F9",
        DataStatisticsAssessmentFooterTextbtn: "#000000",
        DataStatisticsAssessmentBackground: "white",
        DataStatisticsAssessmentFooterBackgroundBtn: "white",
        TestBackground: "#F2F2F6",
        TestcolorText: "#000000",
        VariantTitleColor: "#000000",
        FlagColorSvgBtn: "#000000",
        FooterBackgroundBtn: "#F9F9F9",
        FooterTextBtn:"#000000",
        FooterBackgroundNextBtnSelectedOption: "#F9931C",
        FooterColorNextBtnSelectedOption: "#000000",
        FooterBackgroundBtnDesktop:"#FFFFFF",
        FooterTextBtnDesktop:"#000000",
        FooterFlagMobileButton:'#F9921A',
        HeaderPracticeTestQuestionColors: "#000000",
        OnceTwiceProgressOnesBackground: "#555555",
        CircularTrainerProgressBarColor: "#FFFFFF",
        HptTitleColorText: "#000000",
        HtpPlateBackground: "white",
        HtpIntroductionBtnBackground: "#F9F9F9",
        HtpIntroductionBtnTextColor: "#000000",
        HtpIconNumberBackground: "#555555",
    },
    violetMajesty: {
        headerColors: "#5E299E",
        mainColor: "#E8CCEC",
        textColor: "white",
        btnSettingsColor: "#0078AB",
        btnSettingsColorNotActive: "white",
        textActiveSettingsColor: "white",
        textNotActiveSettingsColor: "#0078AB",
        titleColorSettings: "#5e2a9e",
        hoverColor: "#6B36AB",
        headerSvgColor: "white",
        questionsGroupBackground: "white",
        btnSettingsBackgroundColor: "white",
        svgGroupColor: "#0078AB",
        svgAvtiveBackgroundColor: "#6B36AB",
        toggleBackground: "#E8CBEB",
        toggleBorder: "#BAA2BD",
        QuestionContentBackground: "white",
        VariantBackground: "white",
        VariantTextColor: "#5E2A9E",
        VariantSelectedOption: "white",
        VariantSelectedMockTestOption: "white",
        VariantSelectedMockBackground: "#BC62C8",
        MockTestChartBackground: 'linear-gradient(180deg, rgba(127,198,211,1) 0%, rgba(232,203,235,1) 90%)',
        MockTestChartLabel: "#5E2A9E",
        MockTestChartLinePath: "#5E2A9E",
        MockTestChartPoints: "white",
        DataStatisticsAssessmentTitle: "#5E2A9E",
        DataStatisticsAssessmentContent: "#5E2A9E",
        DataStatisticsAssessmentFooter: "#5E299E",
        DataStatisticsAssessmentFooterTextbtn: "#5E2A9E",
        DataStatisticsAssessmentBackground: "white",
        DataStatisticsAssessmentFooterBackgroundBtn: "white",
        TestBackground: "#E8CCEC",
        TestcolorText: "#5E2A9E",
        VariantTitleColor: "#5E299E",
        FlagColorSvgBtn: "#5E2A9E",
        FooterBackgroundBtn: "#5E299E",
        FooterTextBtn:'white',
        FooterBackgroundNextBtnSelectedOption: "#FFEC4B",
        FooterColorNextBtnSelectedOption: "#5E2A9E",
        FooterBackgroundBtnDesktop:"#FFFFFF",
        FooterTextBtnDesktop:"#5E299E",
        FooterFlagMobileButton:'#F9921A',
        HeaderPracticeTestQuestionColors: "white",
        OnceTwiceProgressOnesBackground: "#BC62C7",
        CircularTrainerProgressBarColor: "#F6EBF8",
        HptTitleColorText: "#5E299E",
        HtpPlateBackground: "white",
        HtpIntroductionBtnBackground: "#5E2A9E",
        HtpIntroductionBtnTextColor: "white",
        HtpIconNumberBackground: "#0078AB",
      },
      nightMode: {
        headerColors: "#1A2836",
        mainColor: "#233448",
        questionsGroupBackground: "#354E65",
        headerSvgColor: "#1E8DEE",
        hoverColor: "#273543",
        btnSettingsColor: "#1A2836",
        btnSettingsColorNotActive: "#334E65",
        textActiveSettingsColor: "white",
        textNotActiveSettingsColor: "white",
        textColor: "white",
        titleColorSettings: "white",
        btnSettingsBackgroundColor: "#334E65",
        svgGroupColor: "white",
        svgAvtiveBackgroundColor: "#233447",
        toggleBackground: "#233447",
        toggleBorder: "#1C2939",
        QuestionContentBackground: "#354E65",
        VariantBackground: "#334E65",
        VariantTextColor: "white",
        VariantSelectedOption: "white",
        VariantSelectedMockTestOption: "#334E65",
        VariantSelectedMockBackground: "#BEB54E",
        MockTestChartBackground: 'linear-gradient(180deg, rgba(151,145,147,1) 0%, rgba(35,52,71,1) 90%)',
        MockTestChartLabel: "white",
        MockTestChartLinePath: "#32EBC3",
        MockTestChartPoints: "white",
        DataStatisticsAssessmentTitle: "white",
        DataStatisticsAssessmentContent: "white",
        DataStatisticsAssessmentFooter: "#1A2836",
        DataStatisticsAssessmentFooterTextbtn: "white",
        DataStatisticsAssessmentBackground: "#354E65",
        DataStatisticsAssessmentFooterBackgroundBtn: "#334E65",
        TestBackground: "#233448",
        TestcolorText: "white",
        VariantTitleColor: "white",
        FlagColorSvgBtn: "white",
        FooterBackgroundBtn: "#1A2836",
        FooterTextBtn:"white",
        FooterBackgroundNextBtnSelectedOption: "#FFEC4B",
        FooterColorNextBtnSelectedOption: "#1EA1F1",
        FooterBackgroundBtnDesktop:"#334E65",
        FooterTextBtnDesktop:"white",
        FooterFlagMobileButton:'#F9921A',
        HeaderPracticeTestQuestionColors: "#1EA1F1",
        OnceTwiceProgressOnesBackground: "#1A2836",
        CircularTrainerProgressBarColor: "#F6EBF8",  
        HptTitleColorText: "white",
        HtpPlateBackground: "#354E65",
        HtpIntroductionBtnBackground: "#1A2836",
        HtpIntroductionBtnTextColor: "#1EA1F1",
        HtpIconNumberBackground: "#0078AB",
    }    
}